#!/usr/bin/env python3
"""Compile reviewed paired-motion variants into a compact runtime database.

The compiler is deliberately boring: no model inference, no network access and no
combat decisions. It only validates, normalizes, filters and deterministically
sorts metadata generated by the offline motion/visual pipeline.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Iterable

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = ROOT / "production/visual_foundry/motion_variants"
DEFAULT_OUTPUT = ROOT / "data/animation/grappling_motion_db_v1.json"

REQUIRED_FEATURES = (
    "technique_id",
    "attack_type",
    "position_id",
    "top_role",
    "mode",
    "phase",
    "reaction_id",
    "gas_bucket",
    "self_grip_signature",
    "opponent_grip_signature",
    "reviewed_connection_signature",
    "previous_clip_id",
)


def _sorted_unique(values: Iterable[Any]) -> list[str]:
    return sorted({str(value) for value in values if str(value)})


def validate_variant(row: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if row.get("version") != "1.0.0":
        errors.append("version_must_be_1.0.0")
    clip_id = str(row.get("clip_id", ""))
    if not clip_id.startswith("gclip_"):
        errors.append("clip_id_must_start_with_gclip_")
    features = row.get("features")
    if not isinstance(features, dict):
        errors.append("features_missing")
        return errors
    for key in REQUIRED_FEATURES:
        if key not in features:
            errors.append(f"feature_missing:{key}")
    if features.get("mode") not in {"gi", "nogi"}:
        errors.append("invalid_mode")
    if features.get("top_role") not in {"neutral", "top", "bottom"}:
        errors.append("invalid_top_role")
    if features.get("gas_bucket") not in {"fresh", "working", "fatigued"}:
        errors.append("invalid_gas_bucket")
    if features.get("phase") not in {"anticipation", "entry", "establish", "stabilize", "response", "recovery", "UNKNOWN"}:
        errors.append("invalid_phase")
    for key in ("self_grip_signature", "opponent_grip_signature", "reviewed_connection_signature"):
        if not isinstance(features.get(key), list):
            errors.append(f"feature_not_array:{key}")
    for key in ("attacker_animation", "defender_animation", "sync_map_ref", "source_ref"):
        if not str(row.get(key, "")):
            errors.append(f"field_missing:{key}")
    if row.get("rights_status") not in {"RESEARCH_ONLY", "COMMERCIAL_DERIVATION_ALLOWED", "BLOCKED"}:
        errors.append("invalid_rights_status")
    if row.get("asset_status") not in {"CANDIDATE", "REVIEWED", "APPROVED_FINAL", "REJECTED"}:
        errors.append("invalid_asset_status")
    if not isinstance(row.get("human_approval"), bool):
        errors.append("human_approval_not_boolean")
    if not isinstance(row.get("shipping"), bool):
        errors.append("shipping_not_boolean")
    return errors


def normalize_variant(row: dict[str, Any]) -> dict[str, Any]:
    features = dict(row["features"])
    for key in ("self_grip_signature", "opponent_grip_signature", "reviewed_connection_signature"):
        features[key] = _sorted_unique(features.get(key, []))
    return {
        "clip_id": str(row["clip_id"]),
        "features": features,
        "attacker_animation": str(row["attacker_animation"]),
        "defender_animation": str(row["defender_animation"]),
        "sync_map_ref": str(row["sync_map_ref"]),
        "contact_signature": _sorted_unique(row.get("contact_signature", [])),
        "source_ref": str(row["source_ref"]),
        "rights_status": str(row["rights_status"]),
        "human_approval": bool(row["human_approval"]),
        "asset_status": str(row["asset_status"]),
        "shipping": bool(row["shipping"]),
    }


def eligible_for_shipping(row: dict[str, Any]) -> bool:
    return (
        row.get("rights_status") == "COMMERCIAL_DERIVATION_ALLOWED"
        and row.get("human_approval") is True
        and row.get("asset_status") == "APPROVED_FINAL"
        and row.get("shipping") is True
    )


def compile_rows(rows: Iterable[dict[str, Any]], shipping_only: bool = True) -> dict[str, Any]:
    clips: list[dict[str, Any]] = []
    seen: set[str] = set()
    rejected: list[dict[str, Any]] = []
    for row in rows:
        errors = validate_variant(row)
        clip_id = str(row.get("clip_id", ""))
        if errors:
            rejected.append({"clip_id": clip_id, "errors": errors})
            continue
        if clip_id in seen:
            rejected.append({"clip_id": clip_id, "errors": ["duplicate_clip_id"]})
            continue
        seen.add(clip_id)
        if shipping_only and not eligible_for_shipping(row):
            continue
        clips.append(normalize_variant(row))
    clips.sort(key=lambda item: item["clip_id"])
    rejected.sort(key=lambda item: item["clip_id"])
    return {
        "$schema": "cria.grappling_motion_db.v1",
        "version": "1.0.0",
        "shipping_only": shipping_only,
        "deterministic_order": "clip_id_ascending",
        "clips": clips,
        "rejected": rejected,
        "runtime_authority": False,
    }


def load_rows(source_dir: Path) -> list[dict[str, Any]]:
    if not source_dir.exists():
        return []
    rows: list[dict[str, Any]] = []
    for path in sorted(source_dir.rglob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(payload, dict) and isinstance(payload.get("variants"), list):
            rows.extend(item for item in payload["variants"] if isinstance(item, dict))
        elif isinstance(payload, dict):
            rows.append(payload)
    return rows


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--include-candidates", action="store_true")
    parser.add_argument("--check", action="store_true", help="Fail if any source variant is invalid or duplicated.")
    args = parser.parse_args()

    rows = load_rows(args.source_dir)
    compiled = compile_rows(rows, shipping_only=not args.include_candidates)
    if args.check and compiled["rejected"]:
        for item in compiled["rejected"]:
            print(f"REJECTED {item['clip_id']}: {', '.join(item['errors'])}")
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(compiled, ensure_ascii=False, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    try:
        shown = args.output.relative_to(ROOT)
    except ValueError:
        shown = args.output
    print(f"Grappling motion DB: {len(compiled['clips'])} clips, {len(compiled['rejected'])} rejected -> {shown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
